# Generated by Django 3.2.7 on 2021-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id_Type_Doc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo documento')),
                ('acronym', models.CharField(max_length=20, verbose_name='Siglas')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
    ]
