# Generated by Django 3.2.7 on 2021-09-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_specialty', models.IntegerField(primary_key=True, serialize=False, verbose_name='Especialidad')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidad',
                'ordering': ['id_specialty'],
            },
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id_file', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ficha')),
                ('trimester', models.IntegerField(verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'ficha',
                'verbose_name_plural': 'fichas',
                'db_table': 'Ficha',
                'ordering': ['id_file'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_Working_Day', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Jornada')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('start_time', models.TimeField(max_length=30, verbose_name=' Hora de Inicio')),
                ('final_hour', models.TimeField(max_length=30, verbose_name='Hora Final')),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
                'db_table': 'Jornada',
                'ordering': ['id_Working_Day'],
            },
        ),
        migrations.CreateModel(
            name='nivel_Formacion',
            fields=[
                ('Education_level', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nivel formacion')),
                ('description', models.CharField(max_length=40, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'nivel_Formacion',
                'verbose_name_plural': 'niveles de formacion',
                'db_table': 'Nivel Formacion',
                'ordering': ['Education_level'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_Rol', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id rol')),
                ('description', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
                'ordering': ['id_Rol'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_Campus', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id sede')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
                'ordering': ['id_Campus'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'ordering': ['id_Type_Doc'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.AlterModelTable(
            name='tipo_documento',
            table='Tipo_Documento',
        ),
        migrations.CreateModel(
            name='Usuaro_Instructor',
            fields=[
                ('id_instructor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id instructor')),
                ('id_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.especialidad')),
                ('id_tipeDoc_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipo_documento')),
            ],
            options={
                'verbose_name': 'Usuario Instructor',
                'verbose_name_plural': 'Usuarios Instructor',
                'db_table': 'Usuario Instructor',
                'ordering': ['id_instructor'],
            },
        ),
        migrations.CreateModel(
            name='usuario_aprendiz',
            fields=[
                ('id_apprentice', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id aprendiz')),
                ('id_tipeDoc_apprentice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipo_documento')),
            ],
            options={
                'verbose_name': 'Usuario Aprendiz',
                'verbose_name_plural': 'Usuarios Aprendices',
                'db_table': 'Usuario Aprendiz',
                'ordering': ['id_apprentice'],
            },
        ),
        migrations.CreateModel(
            name='Usuario_Administrativo',
            fields=[
                ('id_administrative', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id administrativo')),
                ('Id_Tipo_Doc_administrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipo_documento')),
            ],
            options={
                'verbose_name': 'Usuario Administrativo',
                'verbose_name_plural': 'Usuarios Administrativos',
                'db_table': 'Usuario Administrativo',
                'ordering': ['id_administrative'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_User', models.IntegerField(primary_key=True, serialize=False, verbose_name='Usuario')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Segundo Nombre')),
                ('surname', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('second_surname', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
                ('type_Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipo_documento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['id_User'],
            },
        ),
        migrations.CreateModel(
            name='Registro_Asistencia',
            fields=[
                ('id_register', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id registro')),
                ('registration_date', models.CharField(max_length=30, verbose_name='Fecha Registro')),
                ('state', models.CharField(max_length=60, verbose_name='Estado')),
                ('novelty', models.CharField(max_length=60, verbose_name='Novedad')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ficha')),
                ('id_user_Register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('rol_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
            options={
                'verbose_name': 'Registro_Asistencia',
                'verbose_name_plural': 'Registros Asistencias',
                'db_table': 'Reg. Asistencia',
                'ordering': ['id_register'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_program', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id programa')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sede')),
                ('specialty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.especialidad')),
                ('training_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nivel_formacion')),
            ],
            options={
                'verbose_name': 'Programa Academico',
                'verbose_name_plural': 'Programas Academicos',
                'db_table': 'Programa',
                'ordering': ['id_program'],
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='id_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.programa'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='working_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jornada'),
        ),
        migrations.CreateModel(
            name='Asignacion_Ficha',
            fields=[
                ('id_assignment', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Asignacion')),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ficha')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'verbose_name': 'Asignacion Ficha',
                'verbose_name_plural': 'Asignaciones Fichas',
                'db_table': 'Asignación',
                'ordering': ['id_assignment'],
            },
        ),
    ]
